use_frameworks!

platform :ios, '8.0'

target 'MABasicKit_Example' do
  pod 'MABasicKit/Utils', :path => '../'
  pod 'Masonry'
  pod 'MJExtension'

  target 'MABasicKit_Tests' do
    inherit! :search_paths

    
  end
end
